# Generated by Django 2.1 on 2018-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ruta_imagen',
            field=models.FileField(blank=True, default='defecto/defecto.png', null=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateField(blank=True),
        ),
    ]
